modLoader="javafml"
loaderVersion="*"
license="GPL3"
issueTrackerURL="https://github.com/KosmX/emotes/issues"

[[mods]]
modId="emotecraft"
version="${version}"
displayName="Emotecraft"
updateJSONURL="https://api.modrinth.com/updates/emotecraft/forge_updates.json?neoforge=include"
displayURL="https://docs.zigythebird.com/emotecraft/gettingstarted"
logoFile="emotecraft_mod_logo.png"
authors="KosmX, dima_dencep"
credits="Kale Ko, ZigyTheBird, BoBkiNN"
description='''${description}'''

[[mixins]]
config = "emotecraft-arch.mixins.json"

[[dependencies.emotecraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emotecraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emotecraft]]
modId="player_animation_library"
type="required"
versionRange="[1.1.3+alpha.1+mc.1.21.11,)"
ordering="NONE"
side="BOTH"

[[dependencies.emotecraft]]
modId="bendable_cuboids"
type="incompatible"
versionRange="[1.0,1.0.6+mc.1.21.11)"
ordering="NONE"
side="BOTH"
