[versions]
kotlin = "2.0.21"
dokka = "1.8.20"
kotlinx-json = "1.5.1"
kotlinx-coroutines = "1.7.3"

lombok = "1.18.32"
annotations = "23.0.0"
guava = "33.3.1-jre"
gson = "2.10.1"
netty = "4.1.121.Final"
fastutil = "8.5.18"
crowdin = "1.2.1"
config = "1.1.0"
slib = "1.1.7"
bstats = "3.0.2"
luckperms = "5.4"
papi = "2.11.6"
supervanish = "6.2.18-3"

bungeecord = "1.21-R0.5-SNAPSHOT"
velocity = "3.1.1"
paper = "1.18.2-R0.1-SNAPSHOT"

minestom = "39d445482f"

opus-jni = "1.0.3"
opus-concentus = "acaadf2075"
rnnoise-jni = "1.0.2"

shadow = "9.2.2"
grgit = "5.3.3"
buildconfig = "5.7.1"

asm = "9.7.1"

# mockito 5 requires java 11
mockito = "4.1.0"

[libraries]
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-json" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

lombok       = { module = "org.projectlombok:lombok", version.ref = "lombok" }
annotations  = { module = "org.jetbrains:annotations", version.ref = "annotations" }
guava        = { module = "com.google.guava:guava", version.ref = "guava" }
gson         = { module = "com.google.code.gson:gson", version.ref = "gson" }
fastutil     = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
netty        = { module = "io.netty:netty-all", version.ref = "netty"}
crowdin      = { module = "su.plo.crowdin:lib", version.ref = "crowdin" }
config       = { module = "su.plo.config:config", version.ref = "config" }
luckperms    = { module = "net.luckperms:api", version.ref = "luckperms" }
papi         = { module = "me.clip:placeholderapi", version.ref = "papi" }
supervanish  = { module = "com.github.LeonMangler:SuperVanish", version.ref = "supervanish" }

bungeecord   = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord"}
velocity     = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
paper        = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }

opus-jni     = { module = "com.plasmoverse:opus-jni-rust", version.ref = "opus-jni" }
opus-concentus = { module = "com.github.lostromb.concentus:Concentus", version.ref = "opus-concentus" }
rnnoise-jni  = { module = "com.plasmoverse:rnnoise-jni-rust", version.ref = "rnnoise-jni" }

shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

mockito = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }

[plugins]
crowdin = { id = "su.plo.crowdin.plugin", version.ref = "crowdin" }
dokka   = { id = "org.jetbrains.dokka", version.ref = "dokka" }
grgit   = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
