name: Lines of Code

on:
  push:
    branches: [ "main" ]

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate LOC badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          directory: .
          badge: ./loc-badge.svg
          patterns: '*.java|*.kt'

      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add loc-badge.svg
          git commit -m "Update LOC badge" || echo "No changes"
          git push
